services:
    cadastrocurriculo:
        image: cadastrocurriculo
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5000:8080"
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
          mysql:
            condition: service_healthy
        networks:
          - cadastrocurriculo-network

    mysql:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Curricolums
        ports:
          - "3307:3306"
        networks:
          - cadastrocurriculo-network
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 3

volumes:
  mysql-data:

networks:
  cadastrocurriculo-network:
    driver: bridge