version: '3.8'

services:
  cadastrocurriculo:
    image: cadastrocurriculo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mysql
    networks:
      - cadastrocurriculo-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Curricolums
    ports:
      - "3307:3306"
    networks:
      - cadastrocurriculo-network

volumes:
  mysql-data:

networks:
  cadastrocurriculo-network:
    driver: bridge
